# Generated by Django 4.2.3 on 2024-02-27 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True, verbose_name='Token:'),
        ),
    ]
