# Generated by Django 4.2.3 on 2024-04-13 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriasWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
            ],
            options={
                'verbose_name': 'Categoria Web',
                'verbose_name_plural': 'Categorias Web',
            },
        ),
        migrations.CreateModel(
            name='ProyectosWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proyecto', models.CharField(max_length=100)),
                ('contenido_proyecto', models.TextField(verbose_name='Contenido:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado El :')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado El :')),
                ('categoria_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categoriaweb', to='home.categoriasweb')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyecto',
            },
        ),
    ]
