# Generated by Django 4.2.3 on 2024-04-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_categoriasweb_proyectosweb'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectosweb',
            name='enlace_proyecto',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
